version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
      - "./db_dump:/home/db_dump:rw"
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
